version: '3.7'

services:
  app:
    container_name: delivery-app
    build:
      context: .
    # command: sh -c "uwsgi --socket :8000 --master --enable-threads --module cronProjectAPI.wsgi"
    volumes:
      - ./cronDeliveryAPI:/app
      - static_data:/vol/web
    environment:
      # - SECRET_KEY = ps7(e&!!l(kbsmr$76qia@(zi%p=^w-r=(+()ex!33*pyd*8x^
      - ALLOWED_HOSTS=185.125.56.240 127.0.0.1 localhost
    depends_on:
      - db

  proxy:
    build:
      context: ./proxy
    volumes:
      - static_data:/vol/static
    ports:
      - "80:80"
    depends_on:
      - app

  db:
    image: postgres
    ports:
      - "5432"
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=cronadmin
      - POSTGRES_PASSWORD=cronDelivery_1804
      - POSTGRES_DB=crondelivery
    env_file:
      - ./.env

volumes:
  static_data:
