version: '3.7'
services:
  app:
    container_name: delivery-app
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: sh -c "pwd && python3 manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=1
    env_file:
      - ./.env
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=cronadmin
      - POSTGRES_PASSWORD=cronDelivery_1804
      - POSTGRES_DB=crondelivery
    env_file:
      - ./.env
volumes:
  postgres_data:
