version: '3.7'
services:
  web:
    container_name: users-service
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=cronadmin
      - POSTGRES_PASSWORD=cronDelivery_1804
      - POSTGRES_DB=crondelivery
    env_file:
      - ./.env
volumes:
  postgres_data:
