# Generated by Django 3.0.8 on 2020-07-19 14:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderStatus',
            field=models.CharField(choices=[('N', 'Новый'), ('P', 'В Пути'), ('D', 'Доставлен')], default='N', max_length=100, verbose_name='Статус Заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='paymentMode',
            field=models.CharField(default='Наличными курьеру', max_length=100, verbose_name='Способ оплаты'),
        ),
        migrations.AddField(
            model_name='order',
            name='personsAmount',
            field=models.IntegerField(default=1, verbose_name='Количество персон'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+999999999'.Разрешено до 20 символов.", regex='^\\+?1?\\d{9,20}$')], verbose_name='Номер телефона'),
        ),
    ]
