# Generated by Django 3.0.8 on 2020-07-21 13:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200719_1730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Заказанное блюдо', 'verbose_name_plural': 'Заказанные блюда'},
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+999999999'.Разрешено до 20 символов.", regex='^\\+?1?\\d{11,20}$')], verbose_name='Номер телефона'),
        ),
    ]
