# Generated by Django 3.0.8 on 2020-07-24 15:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200721_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+999999999'.Разрешено до 20 символов.", regex='^\\+?1?\\d{11,25}$')], verbose_name='Номер телефона'),
        ),
    ]
