# Generated by Django 3.0.8 on 2020-07-24 16:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200724_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+999999999'.Разрешено до 20 символов.", regex='^\\+?1?\\d{11,25}$')], verbose_name='Номер телефона'),
        ),
    ]
