# Generated by Django 3.0.8 on 2020-07-24 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20200724_1432'),
        ('orders', '0006_auto_20200725_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_items',
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.Order')),
                ('order_dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.CartItem')),
            ],
            options={
                'verbose_name': 'Заказанное блюдо',
                'verbose_name_plural': 'Заказанные блюда',
            },
        ),
    ]
