# Generated by Django 3.0.8 on 2020-08-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_remove_order_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ресторан'),
        ),
    ]
