# Generated by Django 3.0.8 on 2020-08-10 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='restaurant',
        ),
    ]
