# Generated by Django 3.0.8 on 2020-11-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_order_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='Итоговая сумма'),
        ),
    ]
