# Generated by Django 3.0.8 on 2020-07-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='image',
            field=models.CharField(max_length=400, verbose_name='Картинка Блюда'),
        ),
    ]
