# Generated by Django 3.0.8 on 2020-07-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_restaurant_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='not_found.jpg', upload_to='category_imgs', verbose_name='Картинка блюда'),
        ),
    ]
