# Generated by Django 3.0.8 on 2020-07-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название акции')),
                ('discount', models.FloatField(default=0.0, verbose_name='Процент скидки')),
            ],
        ),
    ]
