# Generated by Django 3.0.8 on 2020-07-20 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_offer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'verbose_name': 'Акции', 'verbose_name_plural': 'Акция'},
        ),
    ]
