# Generated by Django 3.0.8 on 2020-07-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20200720_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='categories',
            field=models.ManyToManyField(to='catalog.Category'),
        ),
    ]
