# Generated by Django 3.0.8 on 2020-07-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_offer_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='image',
            field=models.ImageField(default='not_found.jpg', upload_to='logos', verbose_name='Логотип Ресторана'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.ManyToManyField(help_text='Удерживайте CTRL или COMMAND на Mac, чтобы выбрать больше чем одну категорию.', related_name='dishes', to='catalog.Category'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='categories',
            field=models.ManyToManyField(help_text='Удерживайте CTRL или COMMAND на Mac, чтобы выбрать больше чем одну категорию.', to='catalog.Category'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(default='not_found.jpg', upload_to='logos', verbose_name='Логотип Ресторана'),
        ),
    ]
