# Generated by Django 3.0.8 on 2020-07-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20200720_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(default='not_found.jpg', upload_to='restaurant', verbose_name='Картинка ресторана'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(default='not_found.jpg', upload_to='offers', verbose_name='Логотип Ресторана'),
        ),
    ]
