# Generated by Django 3.0.8 on 2020-07-22 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20200722_1716'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RestaurantMenu',
        ),
    ]
