# Generated by Django 3.0.8 on 2020-07-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_delete_restaurantmenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='maxDeliverDist',
            field=models.IntegerField(default=20, verbose_name='Максимальное расстояние для доставки(km)'),
        ),
    ]
