# Generated by Django 3.0.8 on 2020-07-24 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_cartitem_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['-created_at']},
        ),
    ]
