# Generated by Django 3.0.8 on 2020-08-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_remove_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='feedbacksAmount',
            field=models.IntegerField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='rating',
            field=models.FloatField(blank=True, null=True, verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='sumOfPoints',
            field=models.IntegerField(default=0, max_length=200),
        ),
    ]
