# Generated by Django 3.0.8 on 2020-09-13 14:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_auto_20200818_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='restaurant',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ресторан'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='worksFrom',
            field=models.TimeField(default=datetime.datetime(2020, 9, 13, 14, 45, 6, 116528, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='worksTo',
            field=models.TimeField(default=datetime.datetime(2020, 9, 13, 14, 45, 6, 116528, tzinfo=utc)),
        ),
    ]
