# Generated by Django 3.0.8 on 2020-09-13 14:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_auto_20200913_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='workTime',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='worksFrom',
            field=models.TimeField(default=datetime.datetime(2020, 9, 13, 14, 52, 39, 772023, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='worksTo',
            field=models.TimeField(default=datetime.datetime(2020, 9, 13, 14, 52, 39, 772023, tzinfo=utc)),
        ),
    ]
