# Generated by Django 3.0.8 on 2020-09-18 11:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_auto_20200916_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='worksFrom',
            field=models.TimeField(default=datetime.datetime(2020, 9, 18, 11, 59, 23, 199838, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='worksTo',
            field=models.TimeField(default=datetime.datetime(2020, 9, 18, 11, 59, 23, 199838, tzinfo=utc)),
        ),
    ]
