# Generated by Django 3.0.8 on 2020-11-01 22:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_auto_20200918_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='delivery',
            field=models.IntegerField(blank=True, null=True, verbose_name='Стоимость доставки'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='worksFrom',
            field=models.TimeField(default=datetime.datetime(2020, 11, 1, 22, 20, 5, 929246, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='worksTo',
            field=models.TimeField(default=datetime.datetime(2020, 11, 1, 22, 20, 5, 929261, tzinfo=utc)),
        ),
    ]
