# Generated by Django 3.0.8 on 2020-11-01 22:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_auto_20201102_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='worksFrom',
            field=models.TimeField(default=datetime.datetime(2020, 11, 1, 22, 20, 16, 693419, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='worksTo',
            field=models.TimeField(default=datetime.datetime(2020, 11, 1, 22, 20, 16, 693433, tzinfo=utc)),
        ),
    ]
