# Generated by Django 3.0.8 on 2020-11-02 22:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_auto_20201102_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='freeOrder',
            field=models.IntegerField(blank=True, null=True, verbose_name='Бесплатная доставка с суммы заказа от:'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='worksFrom',
            field=models.TimeField(default=datetime.datetime(2020, 11, 2, 22, 44, 48, 143235, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='worksTo',
            field=models.TimeField(default=datetime.datetime(2020, 11, 2, 22, 44, 48, 143253, tzinfo=utc)),
        ),
    ]
