# Generated by Django 3.0.8 on 2020-11-29 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0035_auto_20201128_2135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchingcategory',
            options={'verbose_name': 'Категории для поиска', 'verbose_name_plural': 'Категории для поиска'},
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='worksFrom',
            field=models.TimeField(default=datetime.datetime(2020, 11, 29, 14, 42, 15, 209664)),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='worksTo',
            field=models.TimeField(default=datetime.datetime(2020, 11, 29, 14, 42, 15, 209701)),
        ),
    ]
