# Generated by Django 3.0.8 on 2020-11-29 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0036_auto_20201129_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='worksFrom',
            field=models.TimeField(default=datetime.datetime(2020, 11, 29, 14, 46, 11, 70556)),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='worksTo',
            field=models.TimeField(default=datetime.datetime(2020, 11, 29, 14, 46, 11, 70583)),
        ),
    ]
