# Generated by Django 3.0.8 on 2020-12-02 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0037_auto_20201129_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='worksFrom',
            field=models.TimeField(default=datetime.datetime(2020, 12, 2, 14, 17, 27, 222557)),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='worksTo',
            field=models.TimeField(default=datetime.datetime(2020, 12, 2, 14, 17, 27, 222588)),
        ),
    ]
