# Generated by Django 3.0.8 on 2020-07-27 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0010_remove_order_order_items'),
        ('catalog', '0019_auto_20200726_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overallRate', models.IntegerField()),
                ('pros', models.CharField(default='нет', max_length=255, verbose_name='Плюсы')),
                ('cons', models.CharField(default='нет', max_length=255, verbose_name='Минусы')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='orders.Order')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='catalog.Restaurant')),
            ],
        ),
    ]
