# Generated by Django 3.0.8 on 2020-08-01 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0002_auto_20200728_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='overallRate',
            new_name='overallPoint',
        ),
    ]
