# Generated by Django 3.0.8 on 2020-08-01 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_auto_20200801_1918'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0011_order_comment'),
        ('feedbacks', '0003_auto_20200801_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('overallPoint', models.IntegerField()),
                ('pros', models.CharField(default='нет', max_length=255, verbose_name='Плюсы')),
                ('cons', models.CharField(default='нет', max_length=255, verbose_name='Минусы')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='orders.Order')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='orderFeedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('overallPoint', models.IntegerField()),
                ('pros', models.CharField(default='нет', max_length=255, verbose_name='Плюсы')),
                ('cons', models.CharField(default='нет', max_length=255, verbose_name='Минусы')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='catalog.Restaurant')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='restaurantFeedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantFeedbackImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='feedbacks.RestaurantFeedback')),
            ],
        ),
        migrations.RenameModel(
            old_name='FeedbackImage',
            new_name='OrderFeedbackImage',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.AlterField(
            model_name='orderfeedbackimage',
            name='feedback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='feedbacks.OrderFeedback'),
        ),
    ]
