# Generated by Django 3.0.8 on 2020-11-02 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0005_auto_20200804_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderfeedbackimage',
            name='image',
            field=models.FileField(default='not_found.jpg', upload_to='feedbacks', verbose_name='Картинка ресторана'),
        ),
    ]
