# Generated by Django 3.0.8 on 2020-12-02 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0006_auto_20201103_0144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderfeedback',
            options={'verbose_name_plural': 'Отзывы к заказам'},
        ),
        migrations.AlterModelOptions(
            name='restaurantfeedback',
            options={'verbose_name_plural': 'Отзывы к ресторанам'},
        ),
        migrations.AddField(
            model_name='orderfeedback',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 2, 14, 17, 27, 235310), verbose_name='Заказ создан'),
        ),
        migrations.AddField(
            model_name='restaurantfeedback',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 2, 14, 17, 27, 234441), verbose_name='Отзыв добавлен создан'),
        ),
    ]
