# Generated by Django 3.0.8 on 2020-12-02 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0007_auto_20201202_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantfeedback',
            name='editing',
            field=models.CharField(choices=[('N', 'Не отредактирован'), ('Y', 'Отредактирован')], default='Y', max_length=100, verbose_name='Статус редактирования'),
        ),
        migrations.AlterField(
            model_name='orderfeedback',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 2, 17, 4, 21, 305809), verbose_name='Заказ создан'),
        ),
        migrations.AlterField(
            model_name='restaurantfeedback',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 2, 17, 4, 21, 305150), verbose_name='Отзыв добавлен создан'),
        ),
    ]
