# Generated by Django 3.0.8 on 2020-12-02 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0010_auto_20201202_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderfeedback',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 2, 17, 9, 28, 816698), verbose_name='Заказ создан'),
        ),
        migrations.AlterField(
            model_name='restaurantfeedback',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 2, 17, 9, 28, 816112), verbose_name='Отзыв добавлен создан'),
        ),
        migrations.AlterField(
            model_name='restaurantfeedback',
            name='editing',
            field=models.CharField(choices=[('N', 'Не отредактирован'), ('Y', 'Отредактирован')], default='N', max_length=100, verbose_name='Статус редактирования'),
        ),
    ]
