# Generated by Django 3.0.8 on 2020-12-02 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0011_auto_20201202_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderfeedback',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 2, 17, 10, 19, 851462), verbose_name='Заказ создан'),
        ),
        migrations.AlterField(
            model_name='restaurantfeedback',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 2, 17, 10, 19, 850822), verbose_name='Отзыв добавлен создан'),
        ),
    ]
